### ISSUE TITLE
Might need a better README

### ISSUE THREAD

**Issue by DeboBurro** [yh-luo/flutter_taiwan_zip#1]
How to make this app run on my computer?
eg. dependencies, installation steps and how to build and run

**Comment by yh-luo** [comment]
Hi, please refer to Flutter documentation: [Get started](https://docs.flutter.dev/get-started/install).
This package provides a fully functional example in the example folder, you can easily run it like:
```bash
cd example
flutter run
```
I will provide some screenshots for better illustration!

**Comment by yh-luo** [comment]
Closed by [5c03143](https://github.com/yh-luo/flutter_taiwan_zip/commit/5c031439d2d8de1dc12b7da4c6ede4fcb4c3d9f1)
